<?php

/**
 * ContatosHoteis
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ContatosHoteis extends BaseContatosHoteis
{
	private $table_alias = "contatosHoteis co";

	public function BuscaEndereco()
	{
		try
		{
			//Executa a Query
			$query = Doctrine_Query::create()
			->select('co.*, cc.txt_cidade, cu.txt_uf, cu.cha_sigla')
			->from($this->table_alias)
			->innerJoin("co.CepCidades cc")
			->innerJoin("co.CepUf cu")
			->where("co.cod_idioma = ?", LANGUAGE)
			->execute()
			->toArray();

			//Retorna o resultado
			return $query[0];
		}
		catch (Doctrine_Exception $e)
		{
			echo $e->getMessage();
		}
	}

	public function SelectContatos()
	{
		try
		{
			//Executa a Query
			$query = Doctrine_Query::create()
			->select('co.*, cc.txt_cidade, cu.txt_uf')
			->from($this->table_alias)
			->innerJoin("co.CepCidades cc")
			->innerJoin("co.CepUf cu")
			->where("co.cod_idioma = ?", LANGUAGE)
			->execute()
			->toArray();

			//Retorna o resultado
			return $query[0];
		}
		catch (Doctrine_Exception $e)
		{
			echo $e->getMessage();
		}
	}
}
