<?php

/**
 * EmailsFormularios
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EmailsFormularios extends BaseEmailsFormularios
{
	
public function BuscaDados($id){
	
	
	   try {
	   	
	   	   //Busca os dados
	   	   $recordset = $this->getTable('emailsFormularios')->find($id);

	   	   //Retorna o registro
	   	   return $recordset;
	   	
	   } catch (Doctrine_Exception $e) {
	   	 
	   	     echo $e->getMessage();  
	   }
	
	}

}